"""cascade delete org memberships

Revision ID: 223025400e5e
Revises: c05284fa899e
Create Date: 2025-12-28 18:54:18.350863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223025400e5e'
down_revision: Union[str, Sequence[str], None] = 'c05284fa899e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('memberships_user_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_org_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_org_id_fkey'), 'memberships', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(op.f('memberships_user_id_fkey'), 'memberships', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
