"""use text() for is_active default

Revision ID: d689547d0ade
Revises: 3576081b701d
Create Date: 2025-12-26 19:04:36.323382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd689547d0ade'
down_revision: Union[str, Sequence[str], None] = '3576081b701d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'is_active',
        server_default=sa.text('true'),
        existing_type=sa.Boolean()
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'is_active',
        server_default=None,
        existing_type=sa.Boolean()
    )
    # ### end Alembic commands ###
